// Dictionary of all items in The Escapists
const Item = require('./Item');
module.exports = [
	new Item(13, "Roll of Duct Tape"),
	new Item(25, "Crowbar"),
	new Item(12, "Timber"),
	new Item(76, "Sheet of Metal"),
	new Item(122, "Tool Handle"),
	new Item(119, "Lightweight Pickaxe"),
	new Item(115, "Flimsy Shovel"),
	new Item(114, "Lightweight Shovel"),
	new Item(62, "File"),
	new Item(121, "Lightweight Cutters"),
	new Item(120, "Flimsy Cutters"),
	new Item(61, "Sturdy Cutters"),
	new Item(181, "Multitool"),
	new Item(111, "Knuckle Duster"),
	new Item(19, "Glass Shank"),
	new Item(192, "Wooden Bat"),
	new Item(183, "Spiked Bat"),
	new Item(184, "Durable Contraband Pouch"),
	new Item(99, "Poster"),
	new Item(15, "Magazine"),
	new Item(179, "Nails"),
	new Item(112, "Grapple Head"),
	new Item(180, "Stinger Strip"),
	new Item(93, "Paper Clip"),
	new Item(4, "Inmate Outfit"),
	new Item(127, "POW Outfit"),
	new Item(50, "Book"),
	new Item(95, "Pillow"),
	new Item(144, "Plated POW Outfit"),
	new Item(129, "Padded Inmate Outfit"),
	new Item(130, "Plated Inmate Outfit"),
	new Item(128, "Cushioned Inmate Outfit"),
	new Item(118, "Flimsy Pickaxe"),
	new Item(39, "Sturdy Pickaxe"),
	new Item(5, "Sturdy Shovel"),
	new Item(94, "Razor Blade"),
	new Item(124, "Comb Blade"),
	new Item(110, "Whip"),
	new Item(17, "Comb"),
	new Item(98, "Wire"),
	new Item(10, "Foil"),
	new Item(108, "Nunchucks"),
	new Item(72, "Timber Brace"),
	new Item(75, "Unvarnished Chair"),
	new Item(185, "Cutting Floss"),
	new Item(106, "Game Set"),
	new Item(18, "Glass Shard"),
	new Item(113, "Grappling Hook"),
	new Item(3, "Guard Outfit"),
	new Item(31, "Hoe"),
	new Item(36, "Jar of Ink"),
	new Item(0, "Cell Key"),
	new Item(7, "Utility Key"),
	new Item(6, "Entrance Key"),
	new Item(1, "Staff Key"),
	new Item(43, "Work Key"),
	new Item(84, "Molten Plastic"),
	new Item(96, "Toothbrush"),
	new Item(8, "Lighter"),
	new Item(90, "Cup"),
	new Item(23, "Plastic Spoon"),
	new Item(27, "Plastic Knife"),
	new Item(28, "Plastic Fork"),
	new Item(165, "Family Photo"),
	new Item(116, "Fake Wall Block"),
	new Item(174, "Fake Fence"),
	new Item(137, "Fabric"),
	new Item(44, "Length of Rope"),
	new Item(92, "Circuit Board"),
	new Item(109, "Comb Shiv"),
	new Item(125, "Contraband Pouch"),
	new Item(66, "Cooked Food"),
	new Item(148, "Cookie"),
	new Item(190, "Dodo Donut"),
	new Item(157, "Deluxe Toilet Roll"),
	new Item(126, "Bed Dummy"),
	new Item(69, "Bed Sheet"),
	new Item(73, "Battery"),
	new Item(29, "Baton"),
	new Item(103, "Sock Mace"),
	new Item(46, "Bar of Chocolate"),
	new Item(151, "Bananas"),
	new Item(44, "Balsa Wood"),
	new Item(79, "Bag of Cement"),
	new Item(167, "Dog Tag"),
	new Item(64, "Dirty Inmate Outfit"),
	new Item(26, "Dirt"),
	new Item(153, "ID Papers"),
	new Item(38, "Infirmary Overalls"),
	new Item(101, "Paper Mache"),
	new Item(162, "Pedicure Kit"),
	new Item(191, "Penarium Barrel"),
	new Item(164, "Pocket Watch"),
	new Item(161, "Postcard"),
	new Item(187, "Raft Base"),
	new Item(67, "Vent Cover"),
	new Item(149, "Muffin"),
	new Item(131, "Medkit"),
	new Item(170, "Mango"),
	new Item(261, "Magnet"),
	new Item(146, "Sponge"),
	new Item(68, "Stepladder"),
	new Item(45, "Tube of Toothpaste"),
	new Item(51, "Tube of Super Glue"),
	new Item(52, "Tub of Talcum Powder"),
	new Item(37, "Tub of Bleach"),
	new Item(40, "Trowel"),
	new Item(97, "Toothbrush Shiv"),
	new Item(159, "Teddy Bear"),
	new Item(176, "Uncooked Burrito"),
	new Item(65, "Uncooked Food"),
	new Item(152, "Unsigned ID Papers"),
	new Item(175, "Poncho"),
	new Item(189, "Zipline Hook"),
	new Item(9, "Watch"),
	new Item(53, "Wad of Putty"),
	new Item(32, "Broom"),
	new Item(24, "Screwdriver"),
	new Item(14, "Shaving Cream"),
	new Item(81, "Sheet Rope"),
	new Item(80, "Plunger"),
	new Item(186, "Powered Screwdriver"),
	new Item(60, "Flashlight"),
	new Item(34, "Hammer"),
	new Item(35, "Mop"),
	new Item(150, "Exotic Feather"),
	new Item(16, "Bottle of Sleeping Pills"),
	new Item(10, "Bottle of Medicine"),
	new Item(177, "Burrito"),
	new Item(54, "Candle"),
	new Item(105, "Cup of Molten Chocolate")
];